### ISSUE TITLE
Cannot Scan on Android 12

### ISSUE THREAD

**Issue by ozzy1873** [davejlin/flutter_ble_lib_ios_15#5]
startPeripheralScan returns a permission error on Android 12, even when targeting API 30. Works fine on previous versions of Android.

I/flutter (23347): startPeripheralScan error: BleError (Error code: 0, ATT error code: null, iOS error code: null, Android error code: null, reason: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@400a7aa4: AdapterService getRemoteName, internal message: null, device ID: null, service UUID: null, characteristic UUID: null, descriptor UUID: null)

Appears to be related to this:
https://github.com/dariuszseweryn/RxAndroidBle/pull/767

**Comment by ozzy1873** [comment]
This was due to first trying to target API 31 (which does not work) then going back to API 30. In order to get past the scan error, you have to uninstall/reinstall the app from the phone.

Closing.

**Comment by davejlin** [comment]
@ozzy1873  
thanks for reporting and resolving.
