### ISSUE TITLE
Fatal Build error Xcode 13.1 

### ISSUE THREAD

**Issue by EddieWilkie91** [davejlin/flutter_ble_lib_ios_15#6]
Hi I'm recieving the following build error when building on Xcode 13.1.

![Screenshot 2021-11-11 at 16 27 07](https://user-images.githubusercontent.com/91892512/141333315-b4ef7f1a-13a7-4ca2-b652-319d7757e860.png)

Any ideas why this could be happening? Cheers

Edit: Flutter doctor output
![Screenshot 2021-11-11 at 16 29 46](https://user-images.githubusercontent.com/91892512/141333729-99025bd6-db28-49e5-a21b-f51d6177f320.png)

**Comment by davejlin** [comment]
@EddieWilkie91 thanks for posting the issue ... I don't know off hand - I'm still on Xcode 13.  but I'll look into this shortly, thanks.

**Comment by EddieWilkie91** [comment]
@davejlin No worries thanks. I'm installing Xcode 13.0 just now to see if this makes a difference.

**Comment by EddieWilkie91** [comment]
> @EddieWilkie91 thanks for posting the issue ... I don't know off hand - I'm still on Xcode 13..0 but I'll look into this shortly, thanks.

Retested this with Xcode 13.0 and still have the same issue.

**Comment by EddieWilkie91** [comment]
@davejlin I managed to resolve the issue. I still had some old references to the flutter_ble_lib in my config. I was also using blemulator package too. I've since removed all references and it built with no issues. Closing the ticket, thanks.

**Comment by davejlin** [comment]
@EddieWilkie91 Great to hear you resolved it.  Thanks much for the update.
