### ISSUE TITLE
Possibly update readme with information about this fork

### ISSUE THREAD

**Issue by MoralCode** [davejlin/flutter_ble_lib_ios_15#9]
Hello! I notice the readme still seems to link to the original codebases and pub.dev packages that this project seems to be based on,

I wanted to ask about what the intention behind this repo is so I could determine whether a contribution to update the README might be helpful.

Is this project intended to be an independent fork to replace the original FlutterBleLib in the long term? is it a fork that's intended to be for making a contribution back to the original project? is it just a temporary fix until this issue is resolved upstream? something else?

**Comment by davejlin** [comment]
Hello @MoralCode ...
I described the intent of this fork very clearly in the first two sentences of the README.
The original project appears to have been abandoned by its authors.
So, I forked and applied some fixes so to enable me to continue using the package and made it available on as [flutter_ble_lib_ios_15 ](https://pub.dev/packages/flutter_ble_lib_ios_15) on pub.dev.
I plan on switching my project over to use a better maintained package when I get the chance.
Do you have any suggestions how I should make it clearer in the README?
Thanks.

**Comment by MoralCode** [comment]
My apologies, I probably could have worded that issue submission better. I saw the section you mentioned about how this project differs from the upstream one and I noticed that things like the pub.dev badge and the install instructions still reference the upstream repo instead of this one.

Since you said this is more of a temporary solution until a better Bluetooth library is found, it seems like my minor changes are probably more annoying then helpful, so I apologize for wasting your time.

**Comment by davejlin** [comment]
@MoralCode No worries, and thanks much for your concern. :-)

**Comment by davejlin** [comment]
@MoralCode btw, would you happen to know if there's a reverse lookup from GitHub repos to pub.dev packages?  I know pub.dev packages link to the source repos, usually hosted on GitHub.  But I couldn't find any easy way of going the other direction.  Thanks!

**Comment by MoralCode** [comment]
> @MoralCode btw, would you happen to know if there's a reverse lookup from GitHub repos to pub.dev packages?  I know pub.dev packages link to the source repos, usually hosted on GitHub.  But I couldn't find any easy way of going the other direction.  Thanks!

I dont think theres a formal service for this. I usually rely on links in the README (like badges or references to the name under the install instructions) or in the sidebar of a GH repo to get to a package on the languages respective package manager
